import { ScoringConfig } from '../types/diagnostic.js';

export const scoringConfig: ScoringConfig = {
  categories: [
    {
      key: 'challenge',
      label: 'チャレンジ',
      strength: '行動力と結果志向が強く',
      utilization: 'ゴールが明確な場面で主導して進めると価値を出せます。',
      cautionFallback: '勢いで進める反面、細かい制約が増えると力を出しにくいので、ゴールと裁量を確認しながら動きましょう。',
      weights: {
        'workstyle.speed': 0.2,
        'change.seek': 0.1,
        'motivation.achiever': 0.1,
        'motivation.autonomy': 0.08,
        'autonomy.high': 0.08,
        'role.lead': 0.12,
        'impact.deliver_results': 0.15,
        'affect.high_energy': 0.07,
        'cognition.intuition': 0.05,
        'safety.extraversion': 0.05,
        'response.fast': 0.1,
      },
      penalties: {
        'ng.pressure': 0.3,
        'ng.no_autonomy': 0.2,
      },
    },
    {
      key: 'create',
      label: 'クリエイト',
      strength: '発想力と好奇心が豊かで',
      utilization: '新しいアイデアを試しながら形にする役割で力を発揮できます。',
      cautionFallback: 'アイデアが豊富ですが、単調さが続くとエネルギーが落ちがちです。',
      weights: {
        'cognition.intuition': 0.15,
        'workstyle.improvise': 0.12,
        'change.seek': 0.15,
        'motivation.curiosity': 0.18,
        'motivation.growth': 0.15,
        'attention.multitask': 0.08,
        'career.generalist': 0.06,
        'impact.build_systems': 0.03,
        'motivation.autonomy': 0.04,
        'affect.banter': 0.04,
      },
      penalties: {
        'ng.no_change': 0.25,
        'ng.no_autonomy': 0.15,
        'ng.silent_alone': 0.1,
      },
    },
    {
      key: 'support',
      label: 'サポート',
      strength: '周囲に寄り添いながら支える力が高く',
      utilization: 'チームの安心感をつくりながら調整役を担うと良さが際立ちます。',
      cautionFallback: '周囲への気配りが得意ですが、急なプレッシャーが続くと疲れやすいタイプです。',
      weights: {
        'team.harmony': 0.2,
        'role.support': 0.18,
        'motivation.connection': 0.15,
        'safety.agreeableness': 0.1,
        'safety.introversion': 0.05,
        'safety.guidance_need': 0.08,
        'autonomy.low': 0.08,
        'affect.empathy_sync': 0.1,
        'affect.deliberate': 0.03,
        'response.slow': 0.03,
      },
      penalties: {
        'ng.pressure': 0.25,
        'ng.fast_response': 0.2,
        'ng.read_air': 0.15,
        'ng.silent_alone': 0.1,
      },
    },
    {
      key: 'strategy',
      label: 'ストラテジー',
      strength: '状況を整理して計画に落とし込むのが得意で',
      utilization: '複雑な課題を分解し、仕組み化する役割で頼られます。',
      cautionFallback: '緻密に組み立てる力が強い反面、過剰に急かされると余裕を失いやすいタイプです。',
      weights: {
        'workstyle.structure': 0.2,
        'workstyle.quality': 0.14,
        'cognition.logic': 0.2,
        'attention.single_task': 0.1,
        'impact.build_systems': 0.12,
        'career.specialist': 0.08,
        'autonomy.low': 0.05,
        'response.fast': 0.02,
        'affect.logical_cool': 0.04,
        'change.avoid': 0.05,
      },
      penalties: {
        'ng.fast_response': 0.2,
        'ng.pressure': 0.15,
      },
    },
  ],
  vectors: [
    {
      key: 'speed',
      label: 'スピード',
      strengthSuffix: 'テンポよく成果を形にできます',
      utilizationAddon: '短いサイクルで検証するチームだとさらに伸びます。',
      weights: {
        'workstyle.speed': 0.35,
        'response.fast': 0.25,
        'impact.deliver_results': 0.2,
        'attention.multitask': 0.1,
        'change.seek': 0.1,
      },
      penalties: {
        'ng.fast_response': 0.3,
        'ng.pressure': 0.1,
      },
    },
    {
      key: 'structure',
      label: 'ストラクチャー',
      strengthSuffix: '手順を整えて着実に前進できます',
      utilizationAddon: '手順やナレッジを仕組み化すると周囲の安心感も高まります。',
      weights: {
        'workstyle.structure': 0.35,
        'workstyle.quality': 0.2,
        'cognition.logic': 0.15,
        'autonomy.low': 0.1,
        'career.specialist': 0.1,
        'impact.build_systems': 0.1,
      },
      penalties: {
        'ng.no_autonomy': 0.15,
        'ng.pressure': 0.1,
      },
    },
    {
      key: 'explore',
      label: 'エクスプロア',
      strengthSuffix: '未知のテーマにも好奇心を向けて広げられます',
      utilizationAddon: '変化のあるプロジェクトで仮説を試し続けると成果につながります。',
      weights: {
        'change.seek': 0.25,
        'motivation.curiosity': 0.2,
        'motivation.growth': 0.2,
        'attention.multitask': 0.1,
        'career.generalist': 0.1,
        'motivation.autonomy': 0.1,
        'impact.build_systems': 0.05,
      },
      penalties: {
        'ng.no_change': 0.3,
        'ng.no_autonomy': 0.15,
      },
    },
    {
      key: 'connect',
      label: 'コネクト',
      strengthSuffix: '人とのつながりを活かして場を温められます',
      utilizationAddon: '関係構築や調整が求められるシーンで頼られるでしょう。',
      weights: {
        'team.harmony': 0.2,
        'motivation.connection': 0.2,
        'safety.extraversion': 0.15,
        'safety.agreeableness': 0.15,
        'affect.empathy_sync': 0.1,
        'response.slow': 0.05,
        'affect.deliberate': 0.05,
        'role.support': 0.1,
      },
      penalties: {
        'ng.read_air': 0.2,
        'ng.silent_alone': 0.2,
        'ng.pressure': 0.1,
      },
    },
  ],
  tieBreakers: {
    categories: ['challenge', 'create', 'strategy', 'support'],
    vectors: ['speed', 'structure', 'explore', 'connect'],
  },
  message: {
    penaltyMessages: {
      'ng.pressure': '強いプレッシャーや詰められる状況が続くと集中が途切れやすいので、自分のペースを守れる余地を確保しましょう。',
      'ng.fast_response': '即レスを求められ続けると疲れてしまうので、合意したリズムで動けるように伝えておきましょう。',
      'ng.read_air': '「空気を読め」と求められ過ぎると息苦しくなるので、率直に話せる場を確保するのが大切です。',
      'ng.silent_alone': '静かで孤立した環境ばかりだとエネルギーが落ちやすいので、ときどき刺激のある場を作りましょう。',
      'ng.no_autonomy': '細かい指示ばかりで自由がないとモチベーションが下がるため、裁量を交渉する工夫が有効です。',
      'ng.no_change': '毎日同じことの繰り返しになると飽きやすいので、変化を作る小さな実験を取り入れましょう。',
    },
    motivationMessages: {
      'motivation.achiever': '短いチャレンジを設定して結果を可視化してみましょう',
      'motivation.approval': '信頼できる人に途中経過を共有しフィードバックをもらいましょう',
      'motivation.contribution': '誰かの役に立つ小さなサポートを計画しましょう',
      'motivation.security': '安心できる場所や時間を先に確保してから取り組みを始めましょう',
      'motivation.curiosity': '興味を引かれるテーマの情報を集める時間を取ってみましょう',
      'motivation.autonomy': '自分で意思決定できる範囲を明確にし、自主的に動ける余地を作りましょう',
      'motivation.connection': '一緒に取り組む仲間とゴールや気持ちを共有する時間を持ちましょう',
      'motivation.growth': '成長を実感できる小さな目標と振り返りの場を設けましょう',
    },
  },
};
